openapi: "3.0.0"

info:
  title: Ценные бумаги
  version: 1.0.0

paths:
  /api/v1/exchange-securities:
    get:
      tags:
        - "exchange-securities, v1"
      summary: Получить все ценные бумаги
      operationId: getExchangeSecurities
      responses:
        "200":
          description: Успешный ответ
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ExchangeSecurityFlatDTO'

  /api/v1/exchange-securities/{uuid}:
    get:
      tags:
        - "exchange-securities, v1"
      summary: Получить ценную бумагу
      operationId: getExchangeSecurityByUuid
      parameters:
        - name: uuid
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: Успешный ответ
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExchangeSecurityFlatDTO'
        "404":
          description: Ценная бумага не найдена
    put:
      tags:
        - "exchange-securities, v1"
      summary: Записать ценную бумагу
      operationId: putExchangeSecurity
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ExchangeSecurityFlatDTO'
      responses:
        "200":
          description: Успешный ответ
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExchangeSecurityFlatDTO'

components:
  schemas:
    ExchangeSecurityGroup:
      type: string
      description: |-
        Группа ценных бумаг:
        - STOCK_INDEX - Индексы
        - STOCK_SHARES - Акции
        - STOCK_BONDS - Облигации
        - CURRENCY_SELT - Валюта
        - FUTURES_FORTS - Фьючерсы
        - FUTURES_OPTIONS - Опционы
        - STOCK_DR - Депозитарные расписки
        - STOCK_FOREIGN_SHARES - Иностранные ц.б.
        - STOCK_EUROBOND - Еврооблигации
        - STOCK_PPIF - Паи ПИФов
        - STOCK_ETF - Биржевые фонды
        - CURRENCY_METAL - Драгоценные металлы
        - STOCK_QNV - Квал. инвесторы
        - STOCK_GCC - Клиринговые сертификаты участия
        - STOCK_DEPOSIT - Депозиты с ЦК
        - CURRENCY_FUTURES - Валютный фьючерс
        - CURRENCY_INDICES - Валютные фиксинги
        - STOCK_MORTGAGE - Ипотечный сертификат
        - OTHER - Другое
      enum:
        - STOCK_INDEX
        - STOCK_SHARES
        - STOCK_BONDS
        - CURRENCY_SELT
        - FUTURES_FORTS
        - FUTURES_OPTIONS
        - STOCK_DR
        - STOCK_FOREIGN_SHARES
        - STOCK_EUROBOND
        - STOCK_PPIF
        - STOCK_ETF
        - CURRENCY_METAL
        - STOCK_QNV
        - STOCK_GCC
        - STOCK_DEPOSIT
        - CURRENCY_FUTURES
        - CURRENCY_INDICES
        - STOCK_MORTGAGE
        - OTHER

    ExchangeSecurityType:
      type: string
      description: |-
        Тип ценной бумаги:
        - COMMON_SHARE - Акция обыкновенная (STOCK_SHARES)
        - PREFERRED_SHARE - Акция привилегированная (STOCK_SHARES)
        - OFZ_BOND - Государственная облигация (STOCK_BONDS)
        - CORPORATE_BOND - Корпоративная облигация (STOCK_BONDS)
        - EXCHANGE_BOND - Биржевая облигация (STOCK_BONDS)
        - PUBLIC_PPIF - Пай открытого ПИФа (STOCK_PPIF)
        - ETF_PPIF - ETF (STOCK_ETF)
        - EXCHANGE_PPIF - Пай биржевого ПИФа (STOCK_PPIF)
        - OTHER - Другое (OTHER)
      enum:
        - COMMON_SHARE
        - PREFERRED_SHARE
        - OFZ_BOND
        - CORPORATE_BOND
        - EXCHANGE_BOND
        - PUBLIC_PPIF
        - ETF_PPIF
        - EXCHANGE_PPIF
        - OTHER

    ExchangeSecurityFlatDTO:
      type: object
      required:
        - uuid
        - secId
        - name
        - shortName
        - isin
        - regNumber
        - faceValue
        - issueDate
        - groupType
        - groupName
        - type
        - typeName
        - marketValue
        - created
        - modified
      properties:
        uuid:
          type: string
          format: uuid
        secId:
          type: string
        name:
          type: string
        shortName:
          type: string
        isin:
          type: string
        regNumber:
          type: string
        faceValue:
          type: number
        issueDate:
          type: string
          format: date
        matDate:
          type: string
          format: date
        daysToRedemption:
          type: integer
        groupType:
          type: string
        groupName:
          type: string
        type:
          type: string
        typeName:
          type: string
        marketValue:
          type: number
        couponValue:
          type: number
        couponPercent:
          type: number
        couponDate:
          type: string
          format: date
        couponFrequency:
          type: integer
        accruedInterest:
          type: number
        couponPeriod:
          type: integer
        created:
          type: integer
          format: int64
        modified:
          type: integer
          format: int64
