openapi: "3.0.0"

info:
  title: Значки
  version: 1.0.0

paths:
  /api/v1/icons:
    get:
      tags:
        - "icons, v1"
      summary: Получить все значки
      operationId: getIcons
      responses:
        "200":
          description: Успешный ответ
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/IconFlatDTO'

  /api/v1/icons/{uuid}:
    get:
      tags:
        - "icons, v1"
      summary: Получить значок
      operationId: getIconByUuid
      parameters:
        - name: uuid
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: Успешный ответ
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IconFlatDTO'
        "404":
          description: Значок не найден
    put:
      tags:
        - "icons, v1"
      summary: Записать значок
      operationId: putIcon
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/IconFlatDTO'
      responses:
        "200":
          description: Успешный ответ
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IconFlatDTO'

components:
  schemas:
    IconFlatDTO:
      type: object
      required:
        - uuid
        - name
        - created
        - modified
      properties:
        uuid:
          type: string
          format: uuid
        name:
          type: string
        bytes:
          type: string
          format: byte
        created:
          type: integer
          format: int64
        modified:
          type: integer
          format: int64
