/*
 Copyright (c) Petr Panteleyev. All rights reserved.
 Licensed under the BSD license. See LICENSE file in the project root for full license information.
 */
package org.panteleyev.money.bundles;

import java.util.ListResourceBundle;

import static org.panteleyev.money.bundles.Internationalization.*;

@SuppressWarnings("unused")
public class UiBundle_ru_RU extends ListResourceBundle {
    @Override
    protected Object[][] getContents() {
        return new Object[][]{
                // Words
                {I18N_WORD_ACCOUNT, "Счёт"},
                {I18N_WORD_ACCOUNTS, "Счета"},
                {I18N_WORD_ACTIVE, "Активен"},
                {I18N_WORD_ADD, "Добавить"},
                {I18N_WORD_AFTER, "После"},
                {I18N_WORD_BALANCE, "Баланс"},
                {I18N_WORD_BEFORE, "Перед"},
                {I18N_WORD_CARD, "Карта"},
                {I18N_WORD_CATEGORIES, "Категории"},
                {I18N_WORD_CATEGORY, "Категория"},
                {I18N_WORD_CITY, "Город"},
                {I18N_WORD_CLEAR, "Очистить"},
                {I18N_WORD_CLOSE, "Закрыть"},
                {I18N_WORD_COLORS, "Цвета"},
                {I18N_WORD_COMMENT, "Комментарий"},
                {I18N_WORD_CONFIRMED, "Подтверждено"},
                {I18N_WORD_CONNECTION, "Соединение"},
                {I18N_WORD_CONTACT, "Контакт"},
                {I18N_WORD_CONTACTS, "Контакты"},
                {I18N_WORD_CONTROLS, "Элементы управления"},
                {I18N_WORD_COUNTERPARTY, "Контрагент"},
                {I18N_WORD_COUNTRY, "Страна"},
                {I18N_WORD_CREDIT, "Кредит"},
                {I18N_WORD_CURRENCIES, "Валюты"},
                {I18N_WORD_CURRENCY, "Валюта"},
                {I18N_WORD_DATE, "Дата"},
                {I18N_WORD_DAY, "День"},
                {I18N_WORD_DEBIT, "Дебет"},
                {I18N_WORD_DELETE, "Удалить"},
                {I18N_WORD_DELTA, "Разница"},
                {I18N_WORD_DESCRIPTION, "Описание"},
                {I18N_WORD_DETAILS, "Детали"},
                {I18N_WORD_DIALOGS, "Диалоги"},
                {I18N_WORD_EDIT, "Редактировать"},
                {I18M_WORD_EXIT, "Выход"},
                {I18N_WORD_EXPENSES, "Расходы"},
                {I18N_WORD_EXPORT, "Экспорт"},
                {I18N_WORD_FONTS, "Шрифты"},
                {I18N_WORD_GENERAL, "Общие"},
                {I18N_WORD_ICONS, "Значки"},
                {I18N_WORD_IMPORT, "Импорт"},
                {I18N_WORD_INCOMES, "Доходы"},
                {I18N_WORD_INTEREST, "Проценты"},
                {I18N_WORD_INVOICE, "Счёт"},
                {I18N_WORD_LOGIN, "Логин"},
                {I18N_WORD_MENU, "Меню"},
                {I18N_WORD_MOBILE, "Мобильный"},
                {I18N_WORD_NAME, "Имя"},
                {I18N_WORD_OPEN, "Открыть"},
                {I18N_WORD_OPTIONS, "Настройки"},
                {I18N_WORD_PASSWORD, "Пароль"},
                {I18N_WORD_PHONE, "Телефон"},
                {I18N_WORD_PLACE, "Место"},
                {I18N_WORD_PORT, "Порт"},
                {I18N_WORD_PROFILE, "Профиль"},
                {I18N_WORD_PROFILES, "Профили"},
                {I18N_WORD_RATE, "Курс"},
                {I18N_WORD_REPORT, "Отчет"},
                {I18N_WORD_REQUESTS, "Запросы"},
                {I18N_WORD_RESET, "Сбросить"},
                {I18N_WORD_SAVE, "Сохранить"},
                {I18N_WORD_SCHEMA, "Схема"},
                {I18N_WORD_SERVER, "Сервер"},
                {I18N_WORD_STATEMENT, "Выписка"},
                {I18N_WORD_STATEMENTS, "Выписки"},
                {I18N_WORD_STREET, "Улица"},
                {I18N_WORD_SUM, "Сумма"},
                {I18N_WORD_SYMBOL, "Символ"},
                {I18N_WORD_TABLES, "Таблицы"},
                {I18N_WORD_TEST, "Тест"},
                {I18N_WORD_TEXT, "Текст"},
                {I18N_WORD_TRANSACTION, "Проводка"},
                {I18N_WORD_TRANSACTIONS, "Проводки"},
                {I18N_WORD_TRANSFER, "Перевод"},
                {I18N_WORD_TYPE, "Тип"},
                {I18N_WORD_UNCONFIRMED, "Не подтверждено"},
                {I18N_WORD_UNTIL, "До"},
                {I18N_WORD_UPDATE, "Изменить"},
                {I18N_WORD_UPLOAD, "Загрузка"},
                {I18N_WORD_WAITING, "Ожидает"},
                {I18N_WORD_ZIP, "Индекс"},
                // Menu
                {I18N_MENU_FILE, "Файл"},
                {I18N_MENU_EDIT, "Правка"},
                {I18N_MENU_VIEW, "Вид"},
                {I18N_MENU_TOOLS, "Сервис"},
                {I18N_MENU_WINDOW, "Окно"},
                {I18N_MENU_HELP, "Справка"},
                // Menu items
                {I18N_MENU_ITEM_ABOUT, "О программе"},
                {I18N_MENU_ITEM_ACTIVATE, "Активировать"},
                {I18N_MENU_ITEM_CHECK, "Отметить"},
                {I18N_MENU_ITEM_COPY_NAME, "Копировать название"},
                {I18N_MENU_ITEM_CURRENT_MONTH, "Текущий месяц"},
                {I18N_MENU_ITEM_DEACTIVATE, "Деактивировать"},
                {I18N_MENU_ITEM_NEXT_MONTH, "Следующий месяц"},
                {I18N_MENU_ITEM_PREVIOUS_MONTH, "Предыдущий месяц"},
                {I18N_MENU_ITEM_SEARCH, "Поиск"},
                {I18N_MENU_ITEM_UNCHECK, "Снять отметку"},
                {I18N_MENU_ITEM_UPLOAD, "Загрузить"},
                // Misc
                {I18N_MISC_ACCOUNT_NUMBER, "Номер счёта"},
                {I18N_MISC_ACCOUNTS_CASH_CARDS, "Счета, наличные, карты"},
                {I18N_MISC_ALL_ACCOUNTS, "Все счета"},
                {I18N_MISC_ALL_CATEGORIES, "Все категории"},
                {I18N_MISC_ALL_FILES, "Все файлы"},
                {I18N_MISC_ALL_TYPES, "Все типы"},
                {I18N_MISC_ARE_YOU_SURE, "Вы уверены?"},
                {I18N_MISC_AUTOCOMPLETE_PREFIX_LENGTH, "Длина префикса автодополнения"},
                {I18N_MISC_CARD_NUMBER, "Номер карты"},
                {I18N_MISC_CARD_TYPE, "Тип карты"},
                {I18N_MISC_CLOSING_DATE, "Дата закрытия"},
                {I18N_MISC_CONNECT_AT_STARTUP, "Соединяться при запуске приложения"},
                {I18N_MISC_CREDITED_ACCOUNT, "Счет получателя"},
                {I18N_MISC_DATE_BY_STATEMENT, "Дата по выписке"},
                {I18N_MISC_DATE_PICKER_TOOLTIP, "%s - следующий день\n%s - предыдущий день\n%s - следующий месяц\n%s " +
                        "- предыдущий месяц\n%s - сегодня"},
                {I18N_MISC_DAYS_BEFORE_CLOSING, "Дней до закрытия счета"},
                {I18N_MISC_DEBITED_ACCOUNT, "Исходный счет"},
                {I18N_MISC_DEFAULT_CURRENCY, "Валюта по умолчанию"},
                {I18N_MISC_DEFAULT_PROFILE, "Профиль по умолчанию"},
                {I18N_WORD_ENTITY_NAME, "Название"},
                {I18N_MISC_EXECUTION_DATE_SHORT, "Дата исп."},
                {I18N_MISC_FULL_DUMP, "Полный дамп"},
                {I18N_MISC_FULL_DUMP_IMPORT_CHECK, "Да, я уверен!"},
                {I18N_MISC_FULL_DUMP_IMPORT_WARNING, "Внимание!\nИмпортирование полного дампа полностью уничтожит\n" +
                        "все существующие записи в базе."},
                {I18N_MISC_IGNORE_EXECUTION_DATE, "Игнорировать дату исполнения"},
                {I18N_MISC_IMPORT_FILE_NAME, "Имя файла для импорта"},
                {I18M_MISC_INCOMES_AND_EXPENSES, "Доходы и расходы"},
                {I18N_MISC_INCOMPATIBLE_SCHEMA, "База данных несовместима с приложением, завершение работы."},
                {I18N_MISC_INITIAL_BALANCE, "Начальный баланс"},
                {I18N_MISC_NOT_FOUND, "Не найдено"},
                {I18N_MISC_PARTIAL_IMPORT, "Импорт записей"},
                {I18N_MISC_PROFILE_NAME, "Имя профиля"},
                {I18N_MISC_RECALCULATE_BALANCE, "Пересчитать баланс"},
                {I18N_MISC_RESET_FILTER, "Сбросить фильтр"},
                {I18N_MISC_SCHEMA_RESET, "Сброс базы данных"},
                {I18M_MISC_SCHEMA_RESET_HEADER, "Внимание"},
                {I18N_MISC_SCHEMA_RESET_TEXT, "Все данные будут уничтожены. Проверьте, есть ли резервная копия базы. " +
                        "Продолжать?"},
                {I18N_MISC_SCHEMA_UPDATE, "Обновление базы данных"},
                {I18N_MISC_SCHEMA_UPDATE_TEXT, "Требуется совместимое базы данных. Продолжать?"},
                {I18N_MISC_SHOW_DEACTIVATED_ACCOUNTS, "Показывать неактивные счета"},
                {I18N_MISC_SHOW_THOUSAND_SEPARATOR, "Показывать разделитель тысяч"},
                {I18N_MISC_STATEMENT_BALANCE, "Баланс по выписке"},
                {I18N_MISC_TRANSACTION_DETAILS, "Детали транзакции"},
                {I18N_MISC_UNCHECKED_ONLY, "Только неотмеченные"},
                {I18N_MISC_UPLOAD_DIPLICATE, ": дубликат"},
                {I18N_MISC_UPLOAD_FILES_SKIPPED, "Файлы не загружены:"},
                {I18N_MISC_UPLOAD_TOO_BIG, ": слишком большой"},
                {I18N_MISC_XML_FILES, "Файлы XML"},
                {I18N_CREATE_DESKTOP_ENTRY, "Создать ярлык приложения (Linux)"},
                //
                {"button.Cancel", "Отмена"},
        };
    }
}
