spring:
  profiles:
    active: test
  application:
    name: @project.name@
    version: @project.version@
  liquibase:
    change-log: classpath:liquibase/masterChangelog.xml
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    driverClassName: org.postgresql.Driver

server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /money

management:
  endpoints:
    web:
      exposure:
        include: health,info,env,beans,prometheus
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true