-- Add 'guid'

ALTER TABLE account ADD COLUMN guid VARCHAR(36) NOT NULL DEFAULT '';
UPDATE account SET guid = (SELECT uuid());

ALTER TABLE category ADD COLUMN guid VARCHAR(36) NOT NULL DEFAULT '';
UPDATE category SET guid = (SELECT uuid());

ALTER TABLE contact ADD COLUMN guid VARCHAR(36) NOT NULL DEFAULT '';
UPDATE contact SET guid = (SELECT uuid());

ALTER TABLE currency ADD COLUMN guid VARCHAR(36) NOT NULL DEFAULT '';
UPDATE currency SET guid = (SELECT uuid());

ALTER TABLE transact ADD COLUMN guid VARCHAR(36) NOT NULL DEFAULT '';
UPDATE transact SET guid = (SELECT uuid());

ALTER TABLE transaction_group ADD COLUMN guid VARCHAR(36) NOT NULL DEFAULT '';
UPDATE transaction_group SET guid = (SELECT uuid());

COMMIT;

-- Add 'modified'

ALTER TABLE account ADD COLUMN modified BIGINT NOT NULL DEFAULT 0;
ALTER TABLE category ADD COLUMN modified BIGINT NOT NULL DEFAULT 0;
ALTER TABLE contact ADD COLUMN modified BIGINT NOT NULL DEFAULT 0;
ALTER TABLE currency ADD COLUMN modified BIGINT NOT NULL DEFAULT 0;
ALTER TABLE transact ADD COLUMN modified BIGINT NOT NULL DEFAULT 0;
ALTER TABLE transaction_group ADD COLUMN modified BIGINT NOT NULL DEFAULT 0;
